package dev.anicanon.swiftjava.kotlinaccessors.core;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class KotlinFactoryGenerator {
    private static final Pattern CLASS_NAME_PATTERN = Pattern.compile(
        "(?m)^public\\s+(?:final\\s+)?class\\s+(\\w+)"
    );
    private static final Pattern STATIC_INIT_PATTERN = Pattern.compile(
        "(?m)^\\s*public static (\\w+) init\\(([^)]*)\\)\\s*\\{"
    );
    private static final Pattern PACKAGE_PATTERN = Pattern.compile(
        "(?m)^package\\s+([\\w.]+);\\s*$"
    );

    public String generate(String javaSource) {
        String className = extractClassName(javaSource);
        if (className == null) {
            return null;
        }

        List<InitMethod> initMethods = findInitMethods(javaSource, className);
        if (initMethods.isEmpty()) {
            return null;
        }

        String packageName = extractPackageName(javaSource);
        StringBuilder kt = new StringBuilder();
        kt.append("// Generated by swift-java-kotlin-accessors. Do not edit.\n");
        if (packageName != null) {
            kt.append("package ").append(packageName).append("\n");
        }
        kt.append("\n");

        for (InitMethod method : initMethods) {
            String params = method.parameters;
            String args = buildArguments(params);

            kt.append("fun ").append(className).append("(");
            if (!params.isEmpty()) {
                kt.append(convertToKotlinParams(params));
            }
            kt.append("): ").append(className).append(" =\n");
            kt.append("    ").append(className).append(".`init`(");
            if (!args.isEmpty()) {
                kt.append(args);
            }
            kt.append(")\n\n");
        }

        return kt.toString().stripTrailing() + "\n";
    }

    private String extractClassName(String source) {
        Matcher matcher = CLASS_NAME_PATTERN.matcher(source);
        return matcher.find() ? matcher.group(1) : null;
    }

    private String extractPackageName(String source) {
        Matcher matcher = PACKAGE_PATTERN.matcher(source);
        return matcher.find() ? matcher.group(1) : null;
    }

    private List<InitMethod> findInitMethods(String source, String className) {
        List<InitMethod> methods = new ArrayList<>();
        Matcher matcher = STATIC_INIT_PATTERN.matcher(source);
        while (matcher.find()) {
            String returnType = matcher.group(1);
            if (!returnType.equals(className)) {
                continue;
            }
            String parameters = matcher.group(2).trim();
            // Skip the arena-only init — it has no meaningful parameters
            if (parameters.equals("SwiftArena swiftArena")) {
                continue;
            }
            // Strip trailing SwiftArena parameter if present
            String cleanedParams = stripTrailingArena(parameters);
            methods.add(new InitMethod(cleanedParams));
        }
        return methods;
    }

    private String stripTrailingArena(String parameters) {
        String suffix = ", SwiftArena swiftArena";
        if (parameters.endsWith(suffix)) {
            return parameters.substring(0, parameters.length() - suffix.length());
        }
        return parameters;
    }

    private String convertToKotlinParams(String javaParams) {
        if (javaParams.isEmpty()) {
            return "";
        }
        String[] parts = javaParams.split(",\\s*");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            String param = parts[i].trim();
            int lastSpace = param.lastIndexOf(' ');
            if (lastSpace < 0) continue;
            String type = param.substring(0, lastSpace).trim();
            String name = param.substring(lastSpace + 1).trim();
            if (i > 0) sb.append(", ");
            sb.append(name).append(": ").append(mapToKotlinType(type));
        }
        return sb.toString();
    }

    private String mapToKotlinType(String javaType) {
        return switch (javaType) {
            case "int", "Integer" -> "Int";
            case "long", "Long" -> "Long";
            case "double", "Double" -> "Double";
            case "float", "Float" -> "Float";
            case "boolean", "Boolean" -> "Boolean";
            case "byte", "Byte" -> "Byte";
            case "short", "Short" -> "Short";
            case "char", "Character" -> "Char";
            default -> javaType;
        };
    }

    private String buildArguments(String parameters) {
        if (parameters.isEmpty()) {
            return "";
        }
        String[] parts = parameters.split(",\\s*");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            String param = parts[i].trim();
            int lastSpace = param.lastIndexOf(' ');
            String name = lastSpace >= 0 ? param.substring(lastSpace + 1) : param;
            if (i > 0) sb.append(", ");
            sb.append(name);
        }
        return sb.toString();
    }

    private record InitMethod(String parameters) {}
}
