package dev.anicanon.swiftjava.kotlinaccessors.core;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class KotlinFactoryGenerator {
    private static final Pattern CLASS_NAME_PATTERN = Pattern.compile(
        "(?m)^public\\s+(?:final\\s+)?class\\s+(\\w+)"
    );
    private static final Pattern STATIC_INIT_PATTERN = Pattern.compile(
        "(?m)^\\s*public static (?:(<[^(){}]*>)\\s+)?(\\w+) init\\(([^)]*)\\)"
            + SourceRewriteUtils.THROWS_CLAUSE + "\\s*\\{"
    );
    private static final Pattern ORIGINAL_INIT_PATTERN = Pattern.compile(
        "(?m)^\\s*public static (?:<[^(){}]*>\\s+)?(?:(?:java\\.util\\.)?Optional<(\\w+)>|(\\w+)) init\\(([^)]*)\\)"
    );
    private static final Pattern OPTIONAL_PARAM_PATTERN = Pattern.compile(
        "\\bOptional<([\\w.$\\[\\]<>]+)>\\s+(\\w+)\\b"
    );
    private static final Pattern PRIMITIVE_OPTIONAL_PATTERN = Pattern.compile(
        "\\b(OptionalLong|OptionalInt|OptionalDouble)\\s+(\\w+)\\b"
    );
    private static final Pattern ANNOTATION_PATTERN = Pattern.compile(
        "@[\\w.]+\\s+"
    );

    /**
     * Generate Kotlin factory functions from a Java source file.
     *
     * @param rewrittenSource the rewritten Java source (with Optional params unwrapped)
     * @param originalSource  the original jextract Java source (used to detect Optional params for nullability)
     */
    public String generate(String rewrittenSource, String originalSource) {
        String className = extractClassName(rewrittenSource);
        if (className == null) {
            return null;
        }

        // Build per-method map: param names -> which of them were Optional in the original
        Map<List<String>, Set<String>> optionalsByMethod = findOptionalParamsByMethod(originalSource, className);

        List<InitMethod> initMethods = findInitMethods(rewrittenSource, className, optionalsByMethod);
        if (initMethods.isEmpty()) {
            return null;
        }

        String packageName = extractPackageName(rewrittenSource);
        StringBuilder kt = new StringBuilder();
        kt.append("// Generated by swift-java-kotlin-accessors. Do not edit.\n");
        if (packageName != null) {
            kt.append("package ").append(packageName).append("\n");
        }
        kt.append("\n");

        for (InitMethod method : initMethods) {
            String args = buildArguments(method.parameters);
            KotlinTypeParameters typeParameters = KotlinTypeParameters.from(method.javaTypeParameters);
            String params = typeParameters.inlineSingleUseBounds(method.parameters);
            typeParameters = typeParameters.withoutInlined(method.parameters);
            kt.append("fun ").append(typeParameters.declaration()).append(className).append("(");
            if (!params.isEmpty()) {
                kt.append(convertToKotlinParams(params, method.optionalParamNames));
            }
            kt.append("): ").append(className).append(method.failable ? "?" : "").append(typeParameters.whereClause()).append(" =\n");
            kt.append("    ").append(className).append(".`init`(");
            if (!args.isEmpty()) {
                kt.append(args);
            }
            kt.append(")\n\n");
        }

        return kt.toString().stripTrailing() + "\n";
    }

    /** A Swift failable initializer ({@code init?}) returns null from Java when it fails. */
    private static boolean isFailable(String source, int initStart) {
        int sectionStart = source.lastIndexOf("// ====", initStart);
        String section = source.substring(Math.max(sectionStart, 0), initStart);
        return section.contains("init?(");
    }

    private String extractClassName(String source) {
        Matcher matcher = CLASS_NAME_PATTERN.matcher(source);
        return matcher.find() ? matcher.group(1) : null;
    }

    private String extractPackageName(String source) {
        Matcher matcher = SourceRewriteUtils.PACKAGE_PATTERN.matcher(source);
        return matcher.find() ? matcher.group(1) : null;
    }

    private List<InitMethod> findInitMethods(String source, String className,
                                              Map<List<String>, Set<String>> optionalsByMethod) {
        Map<String, InitMethod> methods = new java.util.LinkedHashMap<>();
        Matcher matcher = STATIC_INIT_PATTERN.matcher(source);
        while (matcher.find()) {
            String returnType = matcher.group(2);
            if (!returnType.equals(className)) {
                continue;
            }
            String parameters = stripAnnotations(matcher.group(3).trim());
            if (parameters.equals("SwiftArena swiftArena")) {
                continue;
            }
            String cleanedParams = stripTrailingArena(parameters);
            List<String> paramNames = extractParamNames(cleanedParams);
            Set<String> optionalNames = optionalsByMethod.getOrDefault(paramNames, Set.of());
            Set<String> optionalParamNames = paramNames.stream()
                .filter(optionalNames::contains)
                .collect(java.util.stream.Collectors.toSet());
            InitMethod method = new InitMethod(cleanedParams, optionalParamNames, isFailable(source, matcher.start()), matcher.group(1));
            String key = SourceRewriteUtils.withArraysAsLists(cleanedParams);
            if (cleanedParams.equals(parameters)) {
                methods.put(key, method);
            } else {
                methods.putIfAbsent(key, method);
            }
        }
        return new ArrayList<>(methods.values());
    }

    /**
     * Builds a per-method map from the original source: (ordered param names) -> (Optional param names).
     * This scopes nullability to the specific method, avoiding false positives when different methods
     * reuse the same param name with different optionality.
     */
    private Map<List<String>, Set<String>> findOptionalParamsByMethod(String originalSource, String className) {
        Map<List<String>, Set<String>> result = new HashMap<>();
        Matcher matcher = ORIGINAL_INIT_PATTERN.matcher(originalSource);
        while (matcher.find()) {
            String returnType = matcher.group(1) != null ? matcher.group(1) : matcher.group(2);
            if (!returnType.equals(className)) {
                continue;
            }
            String params = matcher.group(3).trim();
            Set<String> optionalNames = new HashSet<>();
            for (String part : params.split(",\\s*")) {
                String trimmed = part.trim();
                if (OPTIONAL_PARAM_PATTERN.matcher(trimmed).find()
                    || PRIMITIVE_OPTIONAL_PATTERN.matcher(trimmed).find()) {
                    int lastSpace = trimmed.lastIndexOf(' ');
                    if (lastSpace >= 0) {
                        optionalNames.add(trimmed.substring(lastSpace + 1));
                    }
                }
            }
            if (!optionalNames.isEmpty()) {
                List<String> names = extractParamNames(stripTrailingArena(params));
                result.put(List.copyOf(names), optionalNames);
            }
        }
        return result;
    }

    private List<String> extractParamNames(String parameters) {
        if (parameters.isEmpty()) {
            return List.of();
        }
        List<String> names = new ArrayList<>();
        for (String part : parameters.split(",\\s*")) {
            String trimmed = part.trim();
            int lastSpace = trimmed.lastIndexOf(' ');
            if (lastSpace >= 0) {
                names.add(trimmed.substring(lastSpace + 1));
            }
        }
        return names;
    }

    private String stripAnnotations(String parameters) {
        return ANNOTATION_PATTERN.matcher(parameters).replaceAll("");
    }

    private String stripTrailingArena(String parameters) {
        String stripped = SourceRewriteUtils.stripTrailingArenaParameter(parameters);
        return stripped != null ? stripped : parameters;
    }

    private String convertToKotlinParams(String javaParams, Set<String> optionalParamNames) {
        if (javaParams.isEmpty()) {
            return "";
        }
        String[] parts = javaParams.split(",\\s*");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            String param = parts[i].trim();
            int lastSpace = param.lastIndexOf(' ');
            if (lastSpace < 0) continue;
            String type = param.substring(0, lastSpace).trim();
            String name = param.substring(lastSpace + 1).trim();
            if (i > 0) sb.append(", ");
            String kotlinType = mapToKotlinType(type);
            if (optionalParamNames.contains(name)) {
                kotlinType += "?";
            }
            sb.append(name).append(": ").append(kotlinType);
        }
        return sb.toString();
    }

    private String mapToKotlinType(String javaType) {
        if (javaType.equals("byte[]")) {
            return "ByteArray";
        }
        if (javaType.endsWith("[]")) {
            String elementType = mapToKotlinType(javaType.substring(0, javaType.length() - 2));
            return "Array<" + elementType + ">";
        }
        if (javaType.startsWith("java.util.List<") && javaType.endsWith(">")) {
            String elementType = mapToKotlinType(javaType.substring("java.util.List<".length(), javaType.length() - 1));
            return "List<" + elementType + ">";
        }
        // java.lang.Character -> Char (FQN-qualified, unambiguous)
        // Unqualified "Character" is treated as a domain type and passes through,
        // since swift-java codegen produces domain classes named Character.
        if (javaType.equals("java.lang.Character")) {
            return "Char";
        }
        // Strip java.lang. prefix for other FQN types
        String type = javaType.startsWith("java.lang.") ? javaType.substring("java.lang.".length()) : javaType;
        return switch (type) {
            case "int", "Integer" -> "Int";
            case "long", "Long" -> "Long";
            case "double", "Double" -> "Double";
            case "float", "Float" -> "Float";
            case "boolean", "Boolean" -> "Boolean";
            case "byte", "Byte" -> "Byte";
            case "short", "Short" -> "Short";
            case "char" -> "Char";
            default -> type;
        };
    }

    private String buildArguments(String parameters) {
        return SourceRewriteUtils.invocationArguments(parameters);
    }

    /**
     * Java {@code <T0 extends A & B, T1 extends C>} as Kotlin {@code <T0, T1>} plus a {@code where} clause.
     * A type parameter with a single bound that types exactly one parameter is written as
     * that bound instead, so {@code <T0 extends ProjectClient> init(T0 projectClient)} becomes
     * {@code (projectClient: ProjectClient)}.
     */
    private record KotlinTypeParameters(List<String> names, Map<String, List<String>> bounds) {
        static KotlinTypeParameters from(String javaTypeParameters) {
            List<String> names = new ArrayList<>();
            Map<String, List<String>> bounds = new java.util.LinkedHashMap<>();
            if (javaTypeParameters == null || javaTypeParameters.isBlank()) {
                return new KotlinTypeParameters(names, bounds);
            }
            String body = javaTypeParameters.trim();
            body = body.substring(1, body.length() - 1);
            for (String parameter : body.split(",")) {
                String[] parts = parameter.trim().split("\\s+extends\\s+");
                String name = parts[0].trim();
                names.add(name);
                List<String> nameBounds = new ArrayList<>();
                if (parts.length > 1) {
                    for (String bound : parts[1].split("&")) {
                        nameBounds.add(bound.trim());
                    }
                }
                bounds.put(name, nameBounds);
            }
            return new KotlinTypeParameters(names, bounds);
        }

        private boolean isInlinable(String name, String javaParameters) {
            if (bounds.get(name).size() != 1) {
                return false;
            }
            Matcher uses = Pattern.compile("\\b" + Pattern.quote(name) + "\\b").matcher(javaParameters);
            int count = 0;
            while (uses.find()) {
                count++;
            }
            return count == 1 && Pattern.compile("(^|,\\s*)" + Pattern.quote(name) + "\\s+\\w+\\s*(,|$)").matcher(javaParameters).find();
        }

        String inlineSingleUseBounds(String javaParameters) {
            String result = javaParameters;
            for (String name : names) {
                if (isInlinable(name, javaParameters)) {
                    result = result.replaceAll("\\b" + Pattern.quote(name) + "\\b", Matcher.quoteReplacement(bounds.get(name).get(0)));
                }
            }
            return result;
        }

        KotlinTypeParameters withoutInlined(String javaParameters) {
            List<String> remaining = new ArrayList<>();
            Map<String, List<String>> remainingBounds = new java.util.LinkedHashMap<>();
            for (String name : names) {
                if (!isInlinable(name, javaParameters)) {
                    remaining.add(name);
                    remainingBounds.put(name, bounds.get(name));
                }
            }
            return new KotlinTypeParameters(remaining, remainingBounds);
        }

        String declaration() {
            return names.isEmpty() ? "" : "<" + String.join(", ", names) + "> ";
        }

        String whereClause() {
            List<String> clauses = new ArrayList<>();
            for (String name : names) {
                for (String bound : bounds.get(name)) {
                    clauses.add(name + " : " + bound);
                }
            }
            return clauses.isEmpty() ? "" : " where " + String.join(", ", clauses);
        }
    }

    private record InitMethod(String parameters, Set<String> optionalParamNames, boolean failable, String javaTypeParameters) {}
}
